In [138]:
import pandas as pd 

df = pd.read_csv(
    "../data/raw/OnlineRetail.csv",
    encoding="ISO-8859-1"
)

In [139]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [140]:
df.shape

(541909, 8)

In [141]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [142]:
df.isna().count()

InvoiceNo      541909
StockCode      541909
Description    541909
Quantity       541909
InvoiceDate    541909
UnitPrice      541909
CustomerID     541909
Country        541909
dtype: int64

In [143]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [144]:
df[df["CustomerID"].isna()].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,12/1/2010 14:32,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,12/1/2010 14:32,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,12/1/2010 14:32,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,12/1/2010 14:32,0.43,NaN,United Kingdom

In [145]:
df[df["CustomerID"].isna()]["InvoiceNo"].head(10)

622     536414
1443    536544
1444    536544
1445    536544
1446    536544
1447    536544
1448    536544
1449    536544
1450    536544
1451    536544
Name: InvoiceNo, dtype: object

In [146]:
missing_customer = df[df["CustomerID"].isna()]

In [147]:
missing_customer["InvoiceNo"].nunique()

3710

In [148]:
(missing_customer["UnitPrice"] <= 0 ).sum()

2477

In [149]:
missing_customer["Description"].isna().sum()

1454

Count Negative quantities

In [150]:
(df["Quantity"] < 0).sum()

10624

Count Zero or Negative prices across dataset

In [151]:
(df["UnitPrice"] <= 0).sum()

2517

Invoice number starting with "C"

In [152]:
df["InvoiceNo"].str.startswith("C", na=False).sum()

9288

Whether invoice num beginning with C are associated with negative qunatities

In [153]:
cancelled_invoice = df["InvoiceNo"].str.startswith("C", na=False)
negative_quantitiy = df["Quantity"] < 0

summary= pd.DataFrame({
    "Invoice starts with C" : [
        ((df["InvoiceNo"].str.startswith("C", na=False)) & (df["Quantity"] < 0)).sum(),
        ((df["InvoiceNo"].str.startswith("C", na=False)) & (df["Quantity"] >= 0)).sum()
    ],
    "Invoice does not start with C":[
        ((~df["InvoiceNo"].str.startswith("C", na=False)) & (df["Quantity"] < 0)).sum(),
        ((~df["InvoiceNo"].str.startswith("C", na=False)) & (df["Quantity"] >= 0)).sum()
    ]
}, index=["Negative quantity", "Zero or positive quantity"])

summary

,Invoice starts with C,Invoice does not start with C
Negative quantity,9288,1336
Zero or positive quantity,0,531285

In [154]:
exceptions = df.loc[
    ~df["InvoiceNo"].str.startswith("C", na=False) & (df["Quantity"] < 0)
]

exceptions.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,12/1/2010 16:50,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,12/2/2010 14:42,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,12/3/2010 15:30,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,12/3/2010 15:32,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,12/3/2010 15:33,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,12/3/2010 15:33,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,12/3/2010 15:34,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,12/3/2010 15:35,0.0,NaN,United Kingdom

In [155]:
exceptions["InvoiceNo"].value_counts().head(10)

InvoiceNo
536589    1
562547    1
562544    1
562464    1
562463    1
562391    1
562390    1
562386    1
562385    1
562384    1
Name: count, dtype: int64

In [156]:
exceptions[["Quantity", "UnitPrice", "Description", "CustomerID"]].isna().sum()

Quantity          0
UnitPrice         0
Description     862
CustomerID     1336
dtype: int64

In [157]:
print("Zero-price rows:", (exceptions["UnitPrice"] == 0).sum())
print("Unique invoices:", exceptions["InvoiceNo"].nunique())
print("Total exception rows:", len(exceptions))

Zero-price rows: 1336
Unique invoices: 1336
Total exception rows: 1336

In [158]:
exceptions["StockCode"].nunique()

1082

In [159]:
exceptions["StockCode"].value_counts().head(15)

StockCode
21830     5
85175     5
22719     4
82494L    4
85172     4
72802C    4
79163     3
72807B    3
20966     3
20774     3
40016     3
23084     3
84631     3
72807A    3
85017A    3
Name: count, dtype: int64

In [160]:
exceptions.loc[
    exceptions["Description"].notna(),
    ["InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate"]
].head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate
7313,537032,21275,?,-30,12/3/2010 16:50
13217,537425,84968F,check,-20,12/6/2010 15:35
13218,537426,84968E,check,-35,12/6/2010 15:36
13264,537432,35833G,damages,-43,12/6/2010 16:10
21338,538072,22423,faulty,-13,12/9/2010 14:10
21518,538090,20956,?,-723,12/9/2010 14:48
22296,538161,46000S,Dotcom sales,-100,12/9/2010 17:25
22297,538162,46000M,Dotcom sales,-100,12/9/2010 17:25
42564,540010,22501,reverse 21/5/10 adjustment,-100,1/4/2011 11:13
42566,540012,22502,reverse 21/5/10 adjustment,-100,1/4/2011 11:14
43662,540100,22837,?,-106,1/4/2011 16:53
50806,540558,21258,?,-29,1/10/2011 10:04
50849,540564,22617,"mouldy, thrown away.",-2600,1/10/2011 10:36
51049,540638,72038P,damages,-990,1/10/2011 12:14
51673,540651,82599,?,-290,1/10/2011 15:00

In [161]:
exceptions["Description"].fillna("<MISSING>").value_counts().head(20)

Description
<MISSING>                 862
check                     120
damages                    45
damaged                    42
?                          41
sold as set on dotcom      20
Damaged                    14
thrown away                 9
Unsaleable, destroyed.      9
??                          7
wet damaged                 5
damages?                    5
ebay                        5
smashed                     4
missing                     3
wet pallet                  3
CHECK                       3
mixed up                    2
incorrect stock entry.      2
crushed                     2
Name: count, dtype: int64

In [162]:
exceptions["Quantity"].describe()

count    1336.000000
mean     -154.907934
std       588.292456
min     -9600.000000
25%       -84.000000
50%       -30.000000
75%        -8.000000
max        -1.000000
Name: Quantity, dtype: float64

In [163]:
extreme_records = exceptions.nsmallest(10, "Quantity") 

extreme_records[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
225529,556690,23005,printing smudges/thrown away,-9600,6/14/2011 10:37,0.0,NaN,United Kingdom
225530,556691,23005,printing smudges/thrown away,-9600,6/14/2011 10:37,0.0,NaN,United Kingdom
225528,556687,23003,Printing smudges/thrown away,-9058,6/14/2011 10:36,0.0,NaN,United Kingdom
115818,546152,72140F,throw away,-5368,3/9/2011 17:25,0.0,NaN,United Kingdom
431381,573596,79323W,"Unsaleable, destroyed.",-4830,10/31/2011 15:17,0.0,NaN,United Kingdom
341601,566768,16045,NaN,-3667,9/14/2011 17:53,0.0,NaN,United Kingdom
323458,565304,16259,NaN,-3167,9/2/2011 12:18,0.0,NaN,United Kingdom
263884,560039,20713,wrongly marked. 23343 in box,-3100,7/14/2011 14:27,0.0,NaN,United Kingdom
113580,545990,84598,check,-3000,3/8/2011 13:07,0.0,NaN,United Kingdom
375429,569466,23270,incorrect stock entry.,-2880,10/4/2011 11:42,0.0,NaN,United Kingdom

In [164]:
exceptions.loc[
    exceptions["Quantity"] <= -1000,
    ["InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate"]
    ].sort_values("Quantity")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate
225529,556690,23005,printing smudges/thrown away,-9600,6/14/2011 10:37
225530,556691,23005,printing smudges/thrown away,-9600,6/14/2011 10:37
225528,556687,23003,Printing smudges/thrown away,-9058,6/14/2011 10:36
115818,546152,72140F,throw away,-5368,3/9/2011 17:25
431381,573596,79323W,"Unsaleable, destroyed.",-4830,10/31/2011 15:17
341601,566768,16045,NaN,-3667,9/14/2011 17:53
323458,565304,16259,NaN,-3167,9/2/2011 12:18
263884,560039,20713,wrongly marked. 23343 in box,-3100,7/14/2011 14:27
113580,545990,84598,check,-3000,3/8/2011 13:07
375429,569466,23270,incorrect stock entry.,-2880,10/4/2011 11:42
270886,560600,18007,NaN,-2834,7/19/2011 17:04
431378,573593,79323LP,"Unsaleable, destroyed.",-2618,10/31/2011 15:16
50849,540564,22617,"mouldy, thrown away.",-2600,1/10/2011 10:36
131399,547560,72732,thrown away-can't sell,-2472,3/23/2011 17:28
185113,552733,23059,Thrown away-rusty,-2376,5/11/2011 10:48
431379,573594,79323P,"Unsaleable, destroyed.",-2003,10/31/2011 15:16
323469,565310,21829,?missing,-1897,9/2/2011 12:26
242906,558379,22618,"mouldy, unsaleable.",-1681,6/28/2011 16:34
431376,573591,79323B,"Unsaleable, destroyed.",-1671,10/31/2011 15:15
445127,574816,85036C,damages wax,-1560,11/7/2011 10:37
174654,551837,79164,damages/credits from ASOS.,-1512,5/4/2011 13:23
472841,576764,16008,check,-1510,11/16/2011 13:10
151033,549527,21620,mystery! Only ever imported 1800,-1479,4/8/2011 16:03
375428,569465,23269,incorrect stock entry.,-1440,10/4/2011 11:41
375427,569464,23268,Incorrect stock entry.,-1440,10/4/2011 11:40
234764,557599,23116,Damaged,-1440,6/21/2011 11:34
234740,557597,23115,Damaged,-1440,6/21/2011 11:33
234739,557596,23114,Damaged,-1440,6/21/2011 11:33
229728,557108,23113,Damaged,-1440,6/16/2011 15:58
234765,557600,23117,Damaged,-1440,6/21/2011 11:35
82794,543257,84611B,thrown away,-1430,2/4/2011 16:06
65063,541685,22351,Given away,-1400,1/20/2011 15:41
203761,554553,47566B,incorrectly credited C550456 see 47,-1300,5/25/2011 9:59
203752,554551,47566B,reverse previous adjustment,-1300,5/25/2011 9:58
445128,574822,85036B,damages wax,-1284,11/7/2011 10:38
115505,546130,35610A,thrown away,-1277,3/9/2011 15:08
221186,556242,21700,sold as set on dotcom and amazon,-1206,6/9/2011 16:06
114539,546024,85175,? sold as sets?,-1200,3/8/2011 17:31
431377,573592,79323GR,"Unsaleable, destroyed.",-1158,10/31/2011 15:16
514735,579742,85204,lost??,-1131,11/30/2011 14:34
431383,573598,79342B,"Unsaleable, destroyed.",-1128,10/31/2011 15:18
115488,546124,35610C,Thrown away.,-1121,3/9/2011 14:50
115810,546142,40016,damaged stock,-1100,3/9/2011 16:37
156350,550133,85099F,NaN,-1092,4/14/2011 13:49
285886,561927,22740,?,-1060,8/1/2011 12:49
535335,581212,22578,lost,-1050,12/7/2011 18:38
422751,573115,23343,wrongly coded 20713,-1000,10/27/2011 15:37

In [165]:
(exceptions["Quantity"] <= -1000).sum()

47

In [166]:
df.duplicated().sum()

5268

In [167]:
duplicates = df.loc[
    df.duplicated(keep=False)
].sort_values(
    by = ["InvoiceNo", "StockCode", "InvoiceDate"]
    )

duplicates.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,12/1/2010 11:49,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,12/1/2010 11:49,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,12/1/2010 11:49,2.95,17920.0,United Kingdom

In [168]:
#number of exact duplicates rows 
df.duplicated().sum()

5268

In [169]:
# Rows sharing the same invoice and product code
df.duplicated(
    subset=["InvoiceNo", "StockCode"],
    keep=False
).sum()

20378

In [170]:
grouped = (
    df.groupby(["InvoiceNo", "StockCode"])
    .agg(
            row_count = ("Quantity", "size"),
            different_quantities = ("Quantity", "nunique")
    )
    .reset_index()
)

quantity_variation = grouped[
    (grouped["row_count"] > 1) &
    (grouped["different_quantities"] > 1)
]

quantity_variation.shape[0]

5084

In [171]:
quantity_variation.head(10)

    InvoiceNo StockCode  row_count  different_quantities
135    536381     71270          2                     2
519    536409     85116          2                     2
522    536409    90199C          3                     3
533    536412     21448          5                     2
539    536412     21738          3                     3
542    536412     22077          3                     3
545    536412     22144          2                     2
549    536412     22243          3                     3
551    536412     22273          3                     2
566    536412     22749          3                     2

In [172]:
df.loc[
    (df["InvoiceNo"] == "536412") & 
    (df["StockCode"] == "21448")
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom

In [173]:
df.loc[
    (df["InvoiceNo"] == "536412") & 
    (df["StockCode"] == "21448")
].duplicated().sum()

3

In [174]:
df.duplicated(keep=False).sum()

10147

In [175]:
invoice_dates = pd.to_datetime(
    df["InvoiceDate"],
    format="%m/%d/%Y %H:%M",
    errors="coerce"
)

print("Earliest date:", invoice_dates.min())
print("Latest date:", invoice_dates.max())
print("Dates that failed conversion:", invoice_dates.isna().sum())

Earliest date: 2010-12-01 08:26:00
Latest date: 2011-12-09 12:50:00
Dates that failed conversion: 0

In [176]:
print("Zero unit prices:", (df["UnitPrice"] == 0).sum())
print("Negative unit prices:", (df["UnitPrice"] < 0).sum())
print("Positive unit prices:", (df["UnitPrice"] > 0).sum())

Zero unit prices: 2515
Negative unit prices: 2
Positive unit prices: 539392

In [177]:
invoice_C = df["InvoiceNo"].str.startswith("C", na=False)

invoice_Not_C = ~invoice_C


df["LineRevenue"] = df["Quantity"] * df["UnitPrice"]

df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,LineRevenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom,15.30
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom,25.50
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom,11.10
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom,11.10
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom,54.08

In [178]:
invoice_C = df["InvoiceNo"].str.startswith("C", na=False)
invoice_Not_C = ~invoice_C


num_row_C = invoice_C.sum()
num_row_C_revenue = df.loc[invoice_C, "LineRevenue"].sum()

num_row_not_C = invoice_Not_C.sum()
num_row_not_C_revenue = df.loc[invoice_Not_C, "LineRevenue"].sum()


print("Rows with C invoices:", num_row_C)
print("Revenue from C invoices:", num_row_C_revenue)
print("Rows without C invoices:", num_row_not_C)
print("Revenue from C invoices:", num_row_not_C_revenue)

Rows with C invoices: 9288
Revenue from C invoices: -896812.49
Rows without C invoices: 532621
Revenue from C invoices: 10644560.424000002

In [179]:
exceptions = df.loc[
    invoice_Not_C & (df["Quantity"] < 0)
]

print("Excception Rows: ", len(exceptions))
print("Total exception revenue: ", exceptions["LineRevenue"].sum())
print("Unique Invoices; ", exceptions["InvoiceNo"].nunique())

Excception Rows:  1336
Total exception revenue:  0.0
Unique Invoices;  1336

In [180]:
exceptions["Description"].value_counts(dropna=False).head(15)

Description
NaN                       862
check                     120
damages                    45
damaged                    42
?                          41
sold as set on dotcom      20
Damaged                    14
thrown away                 9
Unsaleable, destroyed.      9
??                          7
wet damaged                 5
damages?                    5
ebay                        5
smashed                     4
missing                     3
Name: count, dtype: int64

In [181]:
result = exceptions["StockCode"].value_counts()

result.head(10)

StockCode
21830     5
85175     5
22719     4
82494L    4
85172     4
72802C    4
79163     3
72807B    3
20966     3
20774     3
Name: count, dtype: int64

## Rule 1: Missing customer ID

In [182]:
df["customer_id_missing"] = df["CustomerID"].isna()

df["customer_id_missing"].sum()

135080

In [183]:
df.loc[
    df["customer_id_missing"],
    ["InvoiceNo", "CustomerID", "Country"]
].head()

     InvoiceNo  CustomerID         Country
622     536414         NaN  United Kingdom
1443    536544         NaN  United Kingdom
1444    536544         NaN  United Kingdom
1445    536544         NaN  United Kingdom
1446    536544         NaN  United Kingdom

In [184]:
df["Description_missing"] = df["Description"].isna()

df["Description_missing"].sum()

1454

In [185]:
df.loc[
    df["Description_missing"],
    "customer_id_missing"
].value_counts()

customer_id_missing
True    1454
Name: count, dtype: int64

In [186]:
total_rows = df.loc[
    (df["customer_id_missing"]& df["Description_missing"]), 
    "customer_id_missing"
].sum()

total_rows

1454

In [187]:
overlap_percentage = (
    total_rows/ df["customer_id_missing"].sum()
) * 100

overlap_percentage

1.0763991708617116

In [188]:
UP_is_0 = (df["UnitPrice"] == 0).sum()
UP_is_less_0 = (df["UnitPrice"] < 0).sum()
UP_is_greater_0 = (df["UnitPrice"] > 0).sum()
UP_is_missing = df["UnitPrice"].isna().sum()

print("UnitePrice is equal to 0: ", UP_is_0)
print("UnitPrice is less than 0: ", UP_is_less_0) 
print("Unitprice is less greater that 0: ", UP_is_greater_0)
print("UnitPrice is missing: ", UP_is_missing)

UnitePrice is equal to 0:  2515
UnitPrice is less than 0:  2
Unitprice is less greater that 0:  539392
UnitPrice is missing:  0

In [189]:
negative_records = df.loc[
    df["UnitPrice"] < 0,
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID"

    ]
]

display(negative_records)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID
299983,A563186,B,Adjust bad debt,1,8/12/2011 14:51,-11062.06,NaN
299984,A563187,B,Adjust bad debt,1,8/12/2011 14:52,-11062.06,NaN

In [190]:
negative_records["LineRevenue"] = (
    negative_records["Quantity"] * negative_records["UnitPrice"]
)

print("Number of records: ", len(negative_records))
print("Total line numbers: ", negative_records["LineRevenue"].sum())

Number of records:  2
Total line numbers:  -22124.12

Records with UnitPrice equal to 0

In [191]:
Zero_price_records = df.loc[
    df["UnitPrice"] == 0,
    
]

Zero_price_records["Description"].value_counts(dropna=False).head(20)

Description
NaN                                1454
check                               159
?                                    47
damages                              45
damaged                              43
found                                25
sold as set on dotcom                20
adjustment                           16
Damaged                              14
Unsaleable, destroyed.                9
thrown away                           9
FRENCH BLUE METAL DOOR SIGN 1         9
FRENCH BLUE METAL DOOR SIGN 8         8
amazon                                8
Found                                 8
FRENCH BLUE METAL DOOR SIGN 4         7
Amazon                                7
FRENCH BLUE METAL DOOR SIGN 3         7
RECIPE BOX PANTRY YELLOW DESIGN       7
OWL DOORSTOP                          7
Name: count, dtype: int64

In [192]:
Qnt_below_0 =( Zero_price_records["Quantity"] < 0).sum()
Qnt_equal_0 = (Zero_price_records["Quantity"] == 0).sum()
Qnt_above_0 = (Zero_price_records["Quantity"] > 0).sum()

print("Quantitiy below 0: ", Qnt_below_0)
print("Quantitiy equal 0: ", Qnt_equal_0)
print("Quantitiy above 0: ", Qnt_above_0)

Quantitiy below 0:  1336
Quantitiy equal 0:  0
Quantitiy above 0:  1179

In [193]:
zero_price_positive_qty = Zero_price_records.loc[
    Zero_price_records["Quantity"] > 0
]

zero_price_positive_qty["Description"].value_counts(
    dropna=False
).head(20)

Description
NaN                                592
check                               39
found                               25
adjustment                          14
FRENCH BLUE METAL DOOR SIGN 1        9
Found                                8
amazon                               8
FRENCH BLUE METAL DOOR SIGN 8        8
OWL DOORSTOP                         7
FRENCH BLUE METAL DOOR SIGN 3        7
RECIPE BOX PANTRY YELLOW DESIGN      7
FRENCH BLUE METAL DOOR SIGN 4        7
FRENCH BLUE METAL DOOR SIGN No       7
Amazon                               7
FRENCH BLUE METAL DOOR SIGN 9        6
Manual                               6
MINT KITCHEN SCALES                  6
?                                    6
RED KITCHEN SCALES                   6
FRENCH BLUE METAL DOOR SIGN 7        6
Name: count, dtype: int64

In [194]:
display(
    zero_price_positive_qty[
        [
            "InvoiceNo",
            "StockCode",
            "Description",
            "Quantity",
            "InvoiceDate",
            "CustomerID",
            "Country"
        ]
    ].sample(15,random_state = 42)
)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,CustomerID,Country
47068,540372,22090,PAPER BUNTING RETROSPOT,24,1/6/2011 16:41,13081.0,United Kingdom
14371,537534,22109,FULL ENGLISH BREAKFAST PLATE,1,12/7/2010 11:48,NaN,United Kingdom
233053,557415,21937,NaN,12,6/20/2011 11:48,NaN,United Kingdom
193552,553539,22414,DOORMAT NEIGHBOURHOOD WITCH,1,5/17/2011 15:27,NaN,United Kingdom
52215,540694,71477,NaN,1,1/11/2011 9:13,NaN,United Kingdom
466074,576302,22812,NaN,46,11/14/2011 14:41,NaN,United Kingdom
233802,557491,85213,NaN,66,6/20/2011 15:08,NaN,United Kingdom
117892,546406,46000S,POLYESTER FILLER PAD 40x40cm,70,3/11/2011 16:21,NaN,United Kingdom
178281,552230,DOT,DOTCOM POSTAGE,1,5/6/2011 15:43,NaN,United Kingdom
242423,558340,22649,STRAWBERRY FAIRY CAKE TEAPOT,1,6/28/2011 14:01,NaN,United Kingdom
352731,567680,23284,NaN,4,9/21/2011 16:17,NaN,United Kingdom
114789,546085,84535A,NaN,144,3/9/2011 11:32,NaN,United Kingdom
193198,553521,22666,RECIPE BOX PANTRY YELLOW DESIGN,1,5/17/2011 14:35,NaN,United Kingdom
193202,553521,22644,CERAMIC CHERRY CAKE MONEY BANK,1,5/17/2011 14:35,NaN,United Kingdom
471148,576620,16207A,NaN,1,11/15/2011 17:02,NaN,United Kingdom

In [195]:
zero_price_positive_qty[
    [
        "CustomerID","Description"
    ]
].isna().sum()

CustomerID     1139
Description     592
dtype: int64

In [196]:
zero_price_positive_qty["CustomerID"].isna().value_counts()

CustomerID
True     1139
False      40
Name: count, dtype: int64

In [197]:
zero_price_with_customer = zero_price_positive_qty.loc[
    zero_price_positive_qty["CustomerID"].notna()
]

display(
    zero_price_with_customer[
        [
            "InvoiceNo",
            "StockCode",
            "Description",
            "Quantity",
            "UnitPrice",
            "CustomerID",
            "Country"
        ]
    ]
)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,0.0,12647.0,Germany
33576,539263,22580,ADVENT CALENDAR GINGHAM SACK,4,0.0,16560.0,United Kingdom
40089,539722,22423,REGENCY CAKESTAND 3 TIER,10,0.0,14911.0,EIRE
47068,540372,22090,PAPER BUNTING RETROSPOT,24,0.0,13081.0,United Kingdom
47070,540372,22553,PLASTERS IN TIN SKULLS,24,0.0,13081.0,United Kingdom
56674,541109,22168,ORGANISER WOOD ANTIQUE WHITE,1,0.0,15107.0,United Kingdom
86789,543599,84535B,FAIRY CAKES NOTEBOOK A6 SIZE,16,0.0,17560.0,United Kingdom
130188,547417,22062,CERAMIC BOWL WITH LOVE HEART DESIGN,36,0.0,13239.0,United Kingdom
139453,548318,22055,MINI CAKE STAND HANGING STRAWBERY,5,0.0,13113.0,United Kingdom
145208,548871,22162,HEART GARLAND RUSTIC PADDED,2,0.0,14410.0,United Kingdom
157042,550188,22636,CHILDS BREAKFAST SET CIRCUS PARADE,1,0.0,12457.0,Switzerland
187613,553000,47566,PARTY BUNTING,4,0.0,17667.0,United Kingdom
198383,554037,22619,SET OF 6 SOLDIER SKITTLES,80,0.0,12415.0,Australia
279324,561284,22167,OVAL WALL MIRROR DIAMANTE,1,0.0,16818.0,United Kingdom
282912,561669,22960,JAM MAKING SET WITH JARS,11,0.0,12507.0,Spain
285657,561916,M,Manual,1,0.0,15581.0,United Kingdom
298054,562973,23157,SET OF 6 NATIVITY MAGNETS,240,0.0,14911.0,EIRE
314745,564651,23270,SET OF 2 CERAMIC PAINTED HEARTS,96,0.0,14646.0,Netherlands
314746,564651,23268,SET OF 2 CERAMIC CHRISTMAS REINDEER,192,0.0,14646.0,Netherlands
314747,564651,22955,36 FOIL STAR CAKE CASES,144,0.0,14646.0,Netherlands
314748,564651,21786,POLKADOT RAIN HAT,144,0.0,14646.0,Netherlands
358655,568158,PADS,PADS TO MATCH ALL CUSHIONS,1,0.0,16133.0,United Kingdom
361825,568384,M,Manual,1,0.0,12748.0,United Kingdom
379913,569716,22778,GLASS CLOCHE SMALL,2,0.0,15804.0,United Kingdom
395529,571035,M,Manual,1,0.0,12446.0,RSA
420404,572893,21208,PASTEL COLOUR HONEYCOMB FAN,5,0.0,18059.0,United Kingdom
436428,574138,23234,BISCUIT TIN VINTAGE CHRISTMAS,216,0.0,12415.0,Australia
436597,574175,22065,CHRISTMAS PUDDING TRINKET POT,12,0.0,14110.0,United Kingdom
436961,574252,M,Manual,1,0.0,12437.0,France
439361,574469,22385,JUMBO BAG SPACEBOY DESIGN,12,0.0,12431.0,Australia
446125,574879,22625,RED KITCHEN SCALES,2,0.0,13014.0,United Kingdom
446793,574920,22899,CHILDREN'S APRON DOLLY GIRL,1,0.0,13985.0,United Kingdom
446794,574920,23480,MINI LIGHTS WOODLAND MUSHROOMS,1,0.0,13985.0,United Kingdom
454463,575579,22437,SET OF 9 BLACK SKULL BALLOONS,20,0.0,13081.0,United Kingdom
454464,575579,22089,PAPER BUNTING VINTAGE PAISLEY,24,0.0,13081.0,United Kingdom
479079,577129,22464,HANGING METAL HEART LANTERN,4,0.0,15602.0,United Kingdom
479546,577168,M,Manual,1,0.0,12603.0,Germany
480649,577314,23407,SET OF 2 TRAYS HOME SWEET HOME,2,0.0,12444.0,Norway
485985,577696,M,Manual,1,0.0,16406.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,0.0,13256.0,United Kingdom

In [198]:
Paid_Invoices = df.loc[
    df["UnitPrice"] > 0,
    "InvoiceNo"
].unique()

zero_price_positive_qty = zero_price_positive_qty.copy()

zero_price_positive_qty["invoice_has_paid_line"] = (
    zero_price_positive_qty["InvoiceNo"].isin(Paid_Invoices)
)

zero_price_positive_qty["invoice_has_paid_line"].value_counts()

invoice_has_paid_line
False    779
True     400
Name: count, dtype: int64

In [199]:
zero_price_positive_qty.groupby(
    "invoice_has_paid_line"
)["InvoiceNo"].nunique()

invoice_has_paid_line
False    766
True      53
Name: InvoiceNo, dtype: int64

In [200]:
mixed_invoices = zero_price_positive_qty.loc[
    zero_price_positive_qty["invoice_has_paid_line"],
    "InvoiceNo"
].unique()

display(
    df.loc[
        df["InvoiceNo"].isin(mixed_invoices),
        [
            "InvoiceNo",
                "StockCode",
                "Description",
                "Quantity",
                "UnitPrice",
                "CustomerID"
        ]
    ].sort_values(["InvoiceNo", "UnitPrice"])
)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,0.00,12647.0
9290,537197,22962,JAM JAR WITH PINK LID,12,0.85,12647.0
9291,537197,22963,JAM JAR WITH GREEN LID,12,0.85,12647.0
9289,537197,22961,JAM MAKING SET PRINTED,12,1.45,12647.0
9297,537197,84050,PINK HEART SHAPE EGG FRYING PAN,6,1.65,12647.0
...,...,...,...,...,...,...
521401,580366,22688,DOORMAT PEACE ON EARTH BLUE,1,8.25,NaN
521411,580366,23050,RECYCLED ACAPULCO MAT GREEN,2,8.25,NaN
521412,580366,23080,RED METAL BOX TOP SECRET,1,8.25,NaN
521400,580366,22624,IVORY KITCHEN SCALES,1,8.50,NaN
521429,580366,23397,FOOT STOOL HOME SWEET HOME,2,9.96,NaN

In [201]:
display(
    df.loc[
        df["InvoiceNo"] == "537197",
        [
            "InvoiceNo",
            "StockCode",
            "Description",
            "Quantity",
            "UnitPrice",
            "CustomerID"
        ]
    ].sort_values("UnitPrice")
)

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,0.00,12647.0
9290,537197,22962,JAM JAR WITH PINK LID,12,0.85,12647.0
9291,537197,22963,JAM JAR WITH GREEN LID,12,0.85,12647.0
9289,537197,22961,JAM MAKING SET PRINTED,12,1.45,12647.0
9297,537197,84050,PINK HEART SHAPE EGG FRYING PAN,6,1.65,12647.0
9298,537197,85055,FRENCH ENAMEL UTENSIL HOLDER,4,3.75,12647.0
9292,537197,84997D,PINK 3 PIECE POLKADOT CUTLERY SET,6,3.75,12647.0
9293,537197,22199,FRYING PAN RED RETROSPOT,4,4.25,12647.0
9294,537197,22200,FRYING PAN PINK POLKADOT,4,4.25,12647.0
9295,537197,22505,MEMO BOARD COTTAGE DESIGN,4,4.95,12647.0
9296,537197,22507,MEMO BOARD RETROSPOT DESIGN,4,4.95,12647.0
9287,537197,22843,BISCUIT TIN VINTAGE GREEN,2,6.75,12647.0
9288,537197,22842,BISCUIT TIN VINTAGE RED,2,6.75,12647.0
9301,537197,22624,IVORY KITCHEN SCALES,2,8.50,12647.0
9299,537197,84968A,SET OF 16 VINTAGE ROSE CUTLERY,1,12.75,12647.0
9303,537197,22847,BREAD BIN DINER STYLE IVORY,1,16.95,12647.0
9300,537197,POST,POSTAGE,3,18.00,12647.0

In [202]:
zero_price_positive_qty["LineRevenue"].sum()

0.0

In [203]:
zero_price_positive_qty["Quantity"].sum()

72603

### Consolidate price-quality findings

In [204]:
price_summary = pd.DataFrame({
    "PriceCategory" : 
    ["Negative",
    "Zero",
    "Posiitve",
    "Missing"],

    "RecordCount" : [
        (df["UnitPrice"] < 0).sum(),
        (df["UnitPrice"] == 0).sum(),
        (df["UnitPrice"] > 0).sum(),
        (df["UnitPrice"]).isna().sum()

    ],

    "LineRevenue": [
        df.loc[df["UnitPrice"] < 0, "LineRevenue"].sum(),
        df.loc[df["UnitPrice"] == 0, "LineRevenue"].sum(),
        df.loc[df["UnitPrice"] > 0, "LineRevenue"].sum(),
        df.loc[df["UnitPrice"].isna() , "LineRevenue"].sum()
    ]
})

price_summary["Precentage"] = (
    price_summary["RecordCount"] / len(df) * 100
).round(2)

display(price_summary)

  PriceCategory  RecordCount  LineRevenue  Precentage
0      Negative            2   -22124.120        0.00
1          Zero         2515        0.000        0.46
2      Posiitve       539392  9769872.054       99.54
3       Missing            0        0.000        0.00

### Investigate price and quantity together

In [ ]:
price_category = pd.Series("positive price", index=df.index)

price_category.loc[df["UnitPrice"] == 0 ] = "Zero price"
price_category.loc[df["UnitPrice"] < 0 ] = "Negative price"
price_category.loc[df["UnitPrice"].isna() ] = "Missing price"

quantitiy_category = pd.Series("positive quantity", index=df.index) 
quantitiy_category.loc[df["Quantity"] == 0] = "Zero quantity"
quantitiy_category.loc[df["Quantity"] < 0] = "Negative quantity"

pd.crosstab(price_category, quantitiy_category)

col_0           Negative quantity  positive quantity
row_0
Negative price                  0                  2
Zero price                   1336               1179
positive price               9288             530104

In [210]:
print("Zero quantities:", (df["Quantity"] == 0).sum())
print("Negative quantities:", (df["Quantity"] < 0).sum())
print("Positive quantities:", (df["Quantity"] > 0).sum())
print("Total records:", len(df))

Zero quantities: 0
Negative quantities: 10624
Positive quantities: 531285
Total records: 541909