In [1]:
import pandas as pd 

df = pd.read_csv(
    "../data/raw/OnlineRetail.csv",
    encoding="ISO-8859-1"
)

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [4]:
df.shape

(541909, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [6]:
df.isna().count()

InvoiceNo      541909
StockCode      541909
Description    541909
Quantity       541909
InvoiceDate    541909
UnitPrice      541909
CustomerID     541909
Country        541909
dtype: int64

In [7]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [8]:
df[df["CustomerID"].isna()].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,12/1/2010 14:32,1.66,NaN,United Kingdom
1448,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1449,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,12/1/2010 14:32,0.43,NaN,United Kingdom
1450,536544,21802,CHRISTMAS TREE HEART DECORATION,9,12/1/2010 14:32,0.43,NaN,United Kingdom
1451,536544,21803,CHRISTMAS TREE STAR DECORATION,11,12/1/2010 14:32,0.43,NaN,United Kingdom

In [10]:
df[df["CustomerID"].isna()]["InvoiceNo"].head(10)

622     536414
1443    536544
1444    536544
1445    536544
1446    536544
1447    536544
1448    536544
1449    536544
1450    536544
1451    536544
Name: InvoiceNo, dtype: object

In [11]:
missing_customer = df[df["CustomerID"].isna()]

In [12]:
missing_customer["InvoiceNo"].nunique()

3710

In [13]:
(missing_customer["UnitPrice"] <= 0 ).sum()

2477

In [14]:
missing_customer["Description"].isna().sum()

1454

Count Negative quantities

In [15]:
(df["Quantity"] < 0).sum()

10624

Count Zero or Negative prices across dataset

In [16]:
(df["UnitPrice"] <= 0).sum()

2517

Invoice number starting with "C"

In [17]:
df["InvoiceNo"].str.startswith("C", na=False).sum()

9288

Whether invoice num beginning with C are associated with negative qunatities

In [29]:
cancelled_invoice = df["InvoiceNo"].str.startswith("C", na=False)
negative_quantitiy = df["Quantity"] < 0

summary= pd.DataFrame({
    "Invoice starts with C" : [
        ((df["InvoiceNo"].str.startswith("C", na=False)) & (df["Quantity"] < 0)).sum(),
        ((df["InvoiceNo"].str.startswith("C", na=False)) & (df["Quantity"] >= 0)).sum()
    ],
    "Invoice does not start with C":[
        ((~df["InvoiceNo"].str.startswith("C", na=False)) & (df["Quantity"] < 0)).sum(),
        ((~df["InvoiceNo"].str.startswith("C", na=False)) & (df["Quantity"] >= 0)).sum()
    ]
}, index=["Negative quantity", "Zero or positive quantity"])

summary

,Invoice starts with C,Invoice does not start with C
Negative quantity,9288,1336
Zero or positive quantity,0,531285

In [31]:
exceptions = df.loc[
    ~df["InvoiceNo"].str.startswith("C", na=False) & (df["Quantity"] < 0)
]

exceptions.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,12/1/2010 16:50,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,12/2/2010 14:42,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,12/3/2010 15:30,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,12/3/2010 15:30,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,12/3/2010 15:32,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,12/3/2010 15:33,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,12/3/2010 15:33,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,12/3/2010 15:34,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,12/3/2010 15:35,0.0,NaN,United Kingdom

In [32]:
exceptions["InvoiceNo"].value_counts().head(10)

InvoiceNo
536589    1
562547    1
562544    1
562464    1
562463    1
562391    1
562390    1
562386    1
562385    1
562384    1
Name: count, dtype: int64

In [33]:
exceptions[["Quantity", "UnitPrice", "Description", "CustomerID"]].isna().sum()

Quantity          0
UnitPrice         0
Description     862
CustomerID     1336
dtype: int64

In [34]:
print("Zero-price rows:", (exceptions["UnitPrice"] == 0).sum())
print("Unique invoices:", exceptions["InvoiceNo"].nunique())
print("Total exception rows:", len(exceptions))

Zero-price rows: 1336
Unique invoices: 1336
Total exception rows: 1336

In [35]:
exceptions["StockCode"].nunique()

1082

In [38]:
exceptions["StockCode"].value_counts().head(15)

StockCode
21830     5
85175     5
22719     4
82494L    4
85172     4
72802C    4
79163     3
72807B    3
20966     3
20774     3
40016     3
23084     3
84631     3
72807A    3
85017A    3
Name: count, dtype: int64

In [37]:
exceptions.loc[
    exceptions["Description"].notna(),
    ["InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate"]
].head(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate
7313,537032,21275,?,-30,12/3/2010 16:50
13217,537425,84968F,check,-20,12/6/2010 15:35
13218,537426,84968E,check,-35,12/6/2010 15:36
13264,537432,35833G,damages,-43,12/6/2010 16:10
21338,538072,22423,faulty,-13,12/9/2010 14:10
21518,538090,20956,?,-723,12/9/2010 14:48
22296,538161,46000S,Dotcom sales,-100,12/9/2010 17:25
22297,538162,46000M,Dotcom sales,-100,12/9/2010 17:25
42564,540010,22501,reverse 21/5/10 adjustment,-100,1/4/2011 11:13
42566,540012,22502,reverse 21/5/10 adjustment,-100,1/4/2011 11:14
43662,540100,22837,?,-106,1/4/2011 16:53
50806,540558,21258,?,-29,1/10/2011 10:04
50849,540564,22617,"mouldy, thrown away.",-2600,1/10/2011 10:36
51049,540638,72038P,damages,-990,1/10/2011 12:14
51673,540651,82599,?,-290,1/10/2011 15:00

In [39]:
exceptions["Description"].fillna("<MISSING>").value_counts().head(20)

Description
<MISSING>                 862
check                     120
damages                    45
damaged                    42
?                          41
sold as set on dotcom      20
Damaged                    14
thrown away                 9
Unsaleable, destroyed.      9
??                          7
wet damaged                 5
damages?                    5
ebay                        5
smashed                     4
missing                     3
wet pallet                  3
CHECK                       3
mixed up                    2
incorrect stock entry.      2
crushed                     2
Name: count, dtype: int64

In [40]:
exceptions["Quantity"].describe()

count    1336.000000
mean     -154.907934
std       588.292456
min     -9600.000000
25%       -84.000000
50%       -30.000000
75%        -8.000000
max        -1.000000
Name: Quantity, dtype: float64

In [44]:
extreme_records = exceptions.nsmallest(10, "Quantity") 

extreme_records[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "InvoiceDate",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
225529,556690,23005,printing smudges/thrown away,-9600,6/14/2011 10:37,0.0,NaN,United Kingdom
225530,556691,23005,printing smudges/thrown away,-9600,6/14/2011 10:37,0.0,NaN,United Kingdom
225528,556687,23003,Printing smudges/thrown away,-9058,6/14/2011 10:36,0.0,NaN,United Kingdom
115818,546152,72140F,throw away,-5368,3/9/2011 17:25,0.0,NaN,United Kingdom
431381,573596,79323W,"Unsaleable, destroyed.",-4830,10/31/2011 15:17,0.0,NaN,United Kingdom
341601,566768,16045,NaN,-3667,9/14/2011 17:53,0.0,NaN,United Kingdom
323458,565304,16259,NaN,-3167,9/2/2011 12:18,0.0,NaN,United Kingdom
263884,560039,20713,wrongly marked. 23343 in box,-3100,7/14/2011 14:27,0.0,NaN,United Kingdom
113580,545990,84598,check,-3000,3/8/2011 13:07,0.0,NaN,United Kingdom
375429,569466,23270,incorrect stock entry.,-2880,10/4/2011 11:42,0.0,NaN,United Kingdom

In [45]:
exceptions.loc[
    exceptions["Quantity"] <= -1000,
    ["InvoiceNo", "StockCode", "Description", "Quantity", "InvoiceDate"]
    ].sort_values("Quantity")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate
225529,556690,23005,printing smudges/thrown away,-9600,6/14/2011 10:37
225530,556691,23005,printing smudges/thrown away,-9600,6/14/2011 10:37
225528,556687,23003,Printing smudges/thrown away,-9058,6/14/2011 10:36
115818,546152,72140F,throw away,-5368,3/9/2011 17:25
431381,573596,79323W,"Unsaleable, destroyed.",-4830,10/31/2011 15:17
341601,566768,16045,NaN,-3667,9/14/2011 17:53
323458,565304,16259,NaN,-3167,9/2/2011 12:18
263884,560039,20713,wrongly marked. 23343 in box,-3100,7/14/2011 14:27
113580,545990,84598,check,-3000,3/8/2011 13:07
375429,569466,23270,incorrect stock entry.,-2880,10/4/2011 11:42
270886,560600,18007,NaN,-2834,7/19/2011 17:04
431378,573593,79323LP,"Unsaleable, destroyed.",-2618,10/31/2011 15:16
50849,540564,22617,"mouldy, thrown away.",-2600,1/10/2011 10:36
131399,547560,72732,thrown away-can't sell,-2472,3/23/2011 17:28
185113,552733,23059,Thrown away-rusty,-2376,5/11/2011 10:48
431379,573594,79323P,"Unsaleable, destroyed.",-2003,10/31/2011 15:16
323469,565310,21829,?missing,-1897,9/2/2011 12:26
242906,558379,22618,"mouldy, unsaleable.",-1681,6/28/2011 16:34
431376,573591,79323B,"Unsaleable, destroyed.",-1671,10/31/2011 15:15
445127,574816,85036C,damages wax,-1560,11/7/2011 10:37
174654,551837,79164,damages/credits from ASOS.,-1512,5/4/2011 13:23
472841,576764,16008,check,-1510,11/16/2011 13:10
151033,549527,21620,mystery! Only ever imported 1800,-1479,4/8/2011 16:03
375428,569465,23269,incorrect stock entry.,-1440,10/4/2011 11:41
375427,569464,23268,Incorrect stock entry.,-1440,10/4/2011 11:40
234764,557599,23116,Damaged,-1440,6/21/2011 11:34
234740,557597,23115,Damaged,-1440,6/21/2011 11:33
234739,557596,23114,Damaged,-1440,6/21/2011 11:33
229728,557108,23113,Damaged,-1440,6/16/2011 15:58
234765,557600,23117,Damaged,-1440,6/21/2011 11:35
82794,543257,84611B,thrown away,-1430,2/4/2011 16:06
65063,541685,22351,Given away,-1400,1/20/2011 15:41
203761,554553,47566B,incorrectly credited C550456 see 47,-1300,5/25/2011 9:59
203752,554551,47566B,reverse previous adjustment,-1300,5/25/2011 9:58
445128,574822,85036B,damages wax,-1284,11/7/2011 10:38
115505,546130,35610A,thrown away,-1277,3/9/2011 15:08
221186,556242,21700,sold as set on dotcom and amazon,-1206,6/9/2011 16:06
114539,546024,85175,? sold as sets?,-1200,3/8/2011 17:31
431377,573592,79323GR,"Unsaleable, destroyed.",-1158,10/31/2011 15:16
514735,579742,85204,lost??,-1131,11/30/2011 14:34
431383,573598,79342B,"Unsaleable, destroyed.",-1128,10/31/2011 15:18
115488,546124,35610C,Thrown away.,-1121,3/9/2011 14:50
115810,546142,40016,damaged stock,-1100,3/9/2011 16:37
156350,550133,85099F,NaN,-1092,4/14/2011 13:49
285886,561927,22740,?,-1060,8/1/2011 12:49
535335,581212,22578,lost,-1050,12/7/2011 18:38
422751,573115,23343,wrongly coded 20713,-1000,10/27/2011 15:37

In [46]:
(exceptions["Quantity"] <= -1000).sum()

47

In [47]:
df.duplicated().sum()

5268

In [48]:
duplicates = df.loc[
    df.duplicated(keep=False)
].sort_values(
    by = ["InvoiceNo", "StockCode", "InvoiceDate"]
    )

duplicates.head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
494,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom
517,536409,21866,UNION JACK FLAG LUGGAGE TAG,1,12/1/2010 11:45,1.25,17908.0,United Kingdom
485,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom
539,536409,22111,SCOTTIE DOG HOT WATER BOTTLE,1,12/1/2010 11:45,4.95,17908.0,United Kingdom
489,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom
527,536409,22866,HAND WARMER SCOTTY DOG DESIGN,1,12/1/2010 11:45,2.10,17908.0,United Kingdom
521,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom
537,536409,22900,SET 2 TEA TOWELS I LOVE LONDON,1,12/1/2010 11:45,2.95,17908.0,United Kingdom
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
612,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
618,536412,21706,FOLDING UMBRELLA RED/WHITE POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
607,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
616,536412,21708,FOLDING UMBRELLA CREAM POLKADOT,1,12/1/2010 11:49,4.95,17920.0,United Kingdom
574,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,12/1/2010 11:49,2.10,17920.0,United Kingdom
594,536412,22141,CHRISTMAS CRAFT TREE TOP ANGEL,1,12/1/2010 11:49,2.10,17920.0,United Kingdom
556,536412,22273,FELTCRAFT DOLL MOLLY,1,12/1/2010 11:49,2.95,17920.0,United Kingdom

In [49]:
#number of exact duplicates rows 
df.duplicated().sum()

5268

In [52]:
# Rows sharing the same invoice and product code
df.duplicated(
    subset=["InvoiceNo", "StockCode"],
    keep=False
).sum()

20378

In [55]:
grouped = (
    df.groupby(["InvoiceNo", "StockCode"])
    .agg(
            row_count = ("Quantity", "size"),
            different_quantities = ("Quantity", "nunique")
    )
    .reset_index()
)

quantity_variation = grouped[
    (grouped["row_count"] > 1) &
    (grouped["different_quantities"] > 1)
]

quantity_variation.shape[0]

5084

In [56]:
quantity_variation.head(10)

    InvoiceNo StockCode  row_count  different_quantities
135    536381     71270          2                     2
519    536409     85116          2                     2
522    536409    90199C          3                     3
533    536412     21448          5                     2
539    536412     21738          3                     3
542    536412     22077          3                     3
545    536412     22144          2                     2
549    536412     22243          3                     3
551    536412     22273          3                     2
566    536412     22749          3                     2

In [57]:
df.loc[
    (df["InvoiceNo"] == "536412") & 
    (df["StockCode"] == "21448")
]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
565,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
578,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
598,536412,21448,12 DAISY PEGS IN WOOD BOX,1,12/1/2010 11:49,1.65,17920.0,United Kingdom
601,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom
604,536412,21448,12 DAISY PEGS IN WOOD BOX,2,12/1/2010 11:49,1.65,17920.0,United Kingdom

In [58]:
df.loc[
    (df["InvoiceNo"] == "536412") & 
    (df["StockCode"] == "21448")
].duplicated().sum()

3

In [60]:
df.duplicated(keep=False).sum()

10147

In [63]:
invoice_dates = pd.to_datetime(
    df["InvoiceDate"],
    format="%m/%d/%Y %H:%M",
    errors="coerce"
)

print("Earliest date:", invoice_dates.min())
print("Latest date:", invoice_dates.max())
print("Dates that failed conversion:", invoice_dates.isna().sum())

Earliest date: 2010-12-01 08:26:00
Latest date: 2011-12-09 12:50:00
Dates that failed conversion: 0

In [64]:
print("Zero unit prices:", (df["UnitPrice"] == 0).sum())
print("Negative unit prices:", (df["UnitPrice"] < 0).sum())
print("Positive unit prices:", (df["UnitPrice"] > 0).sum())

Zero unit prices: 2515
Negative unit prices: 2
Positive unit prices: 539392